@url_base = http://localhost:5003/api/comentario
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtIiwiZXhwIjoxNzUwMjkzMjcwfQ.xcWt5-Ud7MuKm4pTd36j69U73RtKgiGn167iw9tFkCw

### Cadastrar comentário
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "texto" : "Pão com casca é melhor",
    "itemId" : 2
}

### Listar comentários
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### Listar comentários por item
GET {{url_base}}/buscarcomentariosporitem/2
Authorization: Bearer {{token}}