@url_base = http://localhost:5288/api/evento

### Cadastrar evento
POST {{url_base}}/cadastrar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNyIiwiZXhwIjoxNzQ3MTcyNTc4fQ.1rCx3gWuYSkYuWxD5XbaOTUb7ll2H66vvkPDg_uNRpY

{
    "nome" : "Formatura",
    "local" : "Curtibano",
    "data" : "2025-05-12"    
}

### Listar eventos
GET {{url_base}}/listar

### Listar eventos por usuário
GET {{url_base}}/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNyIiwiZXhwIjoxNzQ3MTcyNTc4fQ.1rCx3gWuYSkYuWxD5XbaOTUb7ll2H66vvkPDg_uNRpY