@url_base = http://localhost:5268/api/produto

### Cadastrar produto
POST {{url_base}}/cadastrar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdGUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c3VhcmlvIiwiZXhwIjoxNzQ0Njc2OTc5fQ.d8ZQqD3gkI8s097e2crZMYqu5ujGdBbsVEudpp8KR-U

{
    "nome" : "Bolacha"
}

### Listar produtos
GET {{url_base}}/listar
